services:
  - type: web
    name: lumina-email-generator
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://lumina-email-generator.onrender.com
      - key: RENDER
        value: true 